### ISSUE TITLE
Explore Page

### ISSUE THREAD

**Issue by jthoward64** [UKDanceBlue/danceblue-react-app#145]

**Comment by Jacksonnnnn** [comment]
Attached below is the proposed redesign. From our meeting notes:

- Need to find a way to make it less cluttered (likely won't be as cluttered as the Canva png when implementing).
- Opens with a header of the most recent blog post.
    - The image would be the header for the most recent blog post.
    - The title would have to be responsive to longer blog post titles.
    - The first x amount of characters should be in the description before clicking read more. Generally, the blog post also has a 'read more' section that shows a small synopsis.
- Next section would be the most recent podcast with a play button and the name of the episode. Semantics need to be worked out on this still lol.
- Following the podcast would be an Instagram feed. Ideally, it would show the 9 most recent posts made by the official @uky_danceblue account. Not sure how it would work but if a grid format similar to the app could be followed, that would be amazing. Otherwise whatever works hahaha.
- The final section was originally supposed to be a Twitter feed. Could this still work or should we do something else? YouTube channel feed? Anything with an RSS Feed system will work and be easy to implement.

![Image](https://user-images.githubusercontent.com/12401685/202051746-fc49a675-71bd-4c04-8eb8-8052f358ad80.png)
